package com.bijesh.vocabpowerhouse.ui.main.storage

import java.util.*
import kotlin.collections.ArrayList


internal var vocabList = object : ArrayList<String>(){
    init {
        add("abandon")
                add("abstract")
                add("academy")
                add("acceptable")
                add("access")
                add("accessibility")
                add("acclaimed")
                add("accommodate")
                add("accompany")
                add("accordingly")
                add("accumulate")
                add("accurate")
                add("accustomed")
                add("achieve")
                add("acknowledge")
                add("acquire")
                add("adapt")
                add("adapted")
                add("adequate")
                add("adjacent")
                add("adjust")
                add("administrate")
                add("admittedly")
                add("adult")
                add("advocate")
                add("affect")
                add("aggregate")
                add("aid")
                add("albeit")
                add("allocate")
                add("alter")
                add("alternative")
                add("ambiguous")
                add("amend")
                add("analogy")
                add("analyse")
                add("annual")
                add("anomalies")
                add("anticipate")
                add("apparent")
                add("appeal")
                add("append")
                add("appreciate")
                add("approach")
                add("appropriate")
                add("approximate")
                add("approximately")
                add("arbitrary")
                add("aspect")
                add("assemble")
                add("assess")
                add("assign")
                add("assist")
                add("assistance")
                add("associate")
                add("assume")
                add("assure")
                add("astonishingly")
                add("attach")
                add("attain")
                add("attempt")
                add("attitude")
                add("attribute")
                add("author")
                add("authority")
                add("automate")
                add("available")
                add("avoidance")
                add("aware")

//        B

        add("backbone")
                add("behalf")
                add("behavioural")
                add("beneficial")
                add("benefit")
                add("bestow")
                add("beverages")
                add("bias")
                add("biased")
                add("bond")
                add("boost")
                add("breakthrough")
                add("brief")
                add("bulk")
                add("bygone")
                add("by-product")

        // C
        add("canvas")
                add("capable")
                add("capacity")
                add("casually")
                add("category")
                add("catering")
                add("cease")
                add("challenge")
                add("channel")
                add("charitable")
                add("chemical")
                add("circumstance")
                add("cite")
                add("civil")
                add("clarify")
                add("clause")
                add("closely")
                add("coherent")
                add("coincide")
                add("collapse")
                add("colleague")
                add("commence")
                add("comment")
                add("commission")
                add("commit")
                add("commitment")
                add("commodity")
                add("communicate")
                add("community")
                add("companionship")
                add("compatible")
                add("compensate")
                add("competitive")
                add("compile")
                add("complement")
                add("complex")
                add("component")
                add("compound")
                add("comprehensive")
                add("comprise")
                add("compromise")
                add("compute")
                add("conceive")
                add("concentrate")
                add("concept")
                add("conclude")
                add("concrete")
                add("concurrent")
                add("conduct")
                add("confer")
                add("confine")
                add("confirm")
                add("conflict")
                add("conform")
                add("consent")
                add("consequent")
                add("consequently")
                add("considerable")
                add("consist")
                add("consistency")
                add("consistently")
                add("constant")
                add("constitute")
                add("constrain")
                add("constraints")
                add("construct")
                add("consult")
                add("consume")
                add("consumption")
                add("contact")
                add("context")
                add("contract")
                add("contradict")
                add("contrary")
                add("contrast")
                add("contribute")
                add("controversial")
                add("controversy")
                add("convene")
                add("converse")
                add("convert")
                add("convey")
                add("convince")
                add("cooperate")
                add("coordinate")
                add("core")
                add("corporate")
                add("correspond")
                add("counterpart")
                add("couple")
                add("coverages")
                add("create")
                add("credible")
                add("credit")
                add("crisis")
                add("criteria")
                add("crucial")
                add("culture")
                add("currency")
                add("cycle")

             // D
        add("debate")
                add("decade")
                add("deceptively")
                add("decline")
                add("decrease")
                add("dedicated")
                add("deduce")
                add("deem")
                add("define")
                add("definite")
                add("deforestation")
                add("demanding")
                add("demonstrate")
                add("denote")
                add("deny")
                add("depress")
                add("derive")
                add("design")
                add("desirable")
                add("desperate")
                add("despite")
                add("detect")
                add("detrimental")
                add("deviate")
                add("device")
                add("devote")
                add("differentiate")
                add("dimension")
                add("diminish")
                add("discrete")
                add("discriminate")
                add("displace")
                add("display")
                add("dispose")
                add("distinct")
                add("distinguish")
                add("distort")
                add("distribute")
                add("disturbing")
                add("diverse")
                add("diversity")
                add("document")
                add("domain")
                add("domestic")
                add("dominant")
                add("dominate")
                add("doubtful")
                add("downward")
                add("draft")
                add("drama")
                add("dramatic")
                add("dramatically")
                add("drawback")
                add("duration")
                add("dynamic")

        add("ease")
                add("economy")
                add("edit")
                add("elegantly")
                add("element")
                add("eliminate")
                add("embark")
                add("emerge")
                add("emerged")
                add("emphasis")
                add("empirical")
                add("enable")
                add("encounter")
                add("energy")
                add("enforce")
                add("enhance")
                add("enhancement")
                add("enormous")
                add("enquire")
                add("ensure")
                add("enthusiasm")
                add("enthusiastically")
                add("entity")
                add("environment")
                add("equate")
                add("equip")
                add("equivalent")
                add("erode")
                add("error")
                add("essence")
                add("establish")
                add("estate")
                add("estimate")
                add("ethic")
                add("ethical")
                add("ethically")
                add("ethnic")
                add("evaluate")
                add("evasion")
                add("eventual")
                add("eventually")
                add("evidence")
                add("evident")
                add("evolve")
                add("exceed")
                add("excessively")
                add("exclude")
                add("exclusively")
                add("exhibit")
                add("existence")
                add("expand")
                add("experimental")
                add("expert")
                add("expertise")
                add("explicit")
                add("exploit")
                add("export")
                add("expose")
                add("exposed")
                add("external")
                add("extract")
                add("extremely")

        //F

        add("facilitate")
                add("factor")
                add("fast-paced")
                add("favorable")
                add("favourable")
                add("feasible")
                add("feature")
                add("federal")
                add("fickle")
                add("figure")
                add("file")
                add("final")
                add("finance")
                add("finite")
                add("firmly")
                add("flexible")
                add("fluctuate")
                add("fluctuating")
                add("focus")
                add("format")
                add("formula")
                add("forthcoming")
                add("foundation")
                add("fractal")
                add("framework")
                add("fraught")
                add("frequent")
                add("frequently")
                add("frustration")
                add("function")
                add("fund")
                add("fundamental")
                add("furthermore")

        add("gender")
                add("generate")
                add("generation")
                add("globe")
                add("grade")
                add("gradually")
                add("grant")
                add("grasp")
                add("guarantee")
                add("guideline")

                        add("harness")
                        add("hence")
                        add("heroic")
                        add("hierarchy")
                        add("highlight")
                        add("historically")
                        add("household")
                        add("hypothesis")

        add("identical")
                add("identify")
                add("ideology")
                add("ignorant")
                add("illiteracy")
                add("illustrate")
                add("image")
                add("immense")
                add("immigrate")
                add("impact")
                add("impart")
                add("implant")
                add("implement")
                add("implicate")
                add("implicit")
                add("imply")
                add("impose")
                add("incentive")
                add("incidence")
                add("incline")
                add("income")
                add("incorporate")
                add("increase")
                add("increasingly")
                add("incredibly")
                add("index")
                add("indicate")
                add("individual")
                add("individuality")
                add("induce")
                add("inequality")
                add("inevitable")
                add("inevitably")
                add("infectious")
                add("infer")
                add("infrastructure")
                add("inhabit")
                add("inherent")
                add("inhibit")
                add("initial")
                add("initially")
                add("initiate")
                add("initiated")
                add("injure")
                add("innovate")
                add("insert")
                add("insight")
                add("inspect")
                add("instance")
                add("institute")
                add("institution")
                add("instruct")
                add("insuperable")
                add("integral")
                add("integrate")
                add("integrity")
                add("intellectual")
                add("intelligent")
                add("intense")
                add("interact")
                add("intermediate")
                add("internal")
                add("interpret")
                add("interval")
                add("intervene")
                add("intervention")
                add("intrinsic")
                add("invest")
                add("investigate")
                add("invoke")
                add("involve")
                add("irresistible")
                add("irrespective")
                add("isolate")
                add("issue")

        add("journal")
                add("justify")

                add("labour")
                        add("layer")
                        add("lecture")
                        add("legal")
                        add("legislate")
                        add("legitimate")
                        add("levy")
                        add("liability")
                        add("liberal")
                        add("licence")
                        add("likelihood")
                        add("likely")
                        add("likewise")
                        add("literate")
                        add("locate")
                        add("logic")
                        add("lucrative")

                        add("magnificent")
                                add("maintain")
                                add("major")
                                add("majority")
                                add("mandatory")
                                add("manipulate")
                                add("manual")
                                add("margin")
                                add("marginal")
                                add("maternal")
                                add("mature")
                                add("maximise")
                                add("mechanism")
                                add("media")
                                add("mediate")
                                add("medical")
                                add("medium")
                                add("mental")
                                add("mentally")
                                add("method")
                                add("migrate")
                                add("military")
                                add("minimal")
                                add("minimise")
                                add("minimum")
                                add("ministry")
                                add("minor")
                                add("mobility")
                                add("mode")
                                add("moderately")
                                add("modify")
                                add("monitor")
                                add("motivated")
                                add("motive")
                                add("mutual")
                                add("myriad")

        add("necessities")
                add("necessity")
                add("negate")
                add("neglected")
                add("network")
                add("neutral")
                add("nevertheless")
                add("nonetheless")
                add("norm")
                add("normal")
                add("notion")
                add("notwithstanding")
                add("nuclear")

                add("objective")
                        add("obstacles")
                        add("obtain")
                        add("obtainable")
                        add("obvious")
                        add("obviously")
                        add("occupy")
                        add("occur")
                        add("odd")
                        add("offset")
                        add("ongoing")
                        add("optimism")
                        add("option")
                        add("orient")
                        add("orientation")
                        add("ought")
                        add("outcome")
                        add("overall")
                        add("overlap")
                        add("overseas")

        add("panel")
                add("paradigm")
                add("paragraph")
                add("parallel")
                add("parameter")
                add("participate")
                add("partner")
                add("passive")
                add("patently")
                add("perceive")
                add("perceived")
                add("percent")
                add("period")
                add("persist")
                add("perspective")
                add("phase")
                add("phenomenon")
                add("philosophically")
                add("philosophy")
                add("physical")
                add("pitfalls")
                add("pleasurable")
                add("policy")
                add("popularity")
                add("portfolio")
                add("portion")
                add("pose")
                add("positive")
                add("positively")
                add("potential")
                add("practitioner")
                add("precede")
                add("precise")
                add("predict")
                add("predictable")
                add("predominant")
                add("preliminary")
                add("presume")
                add("prevail")
                add("prevalent")
                add("previous")
                add("primary")
                add("prime")
                add("principal")
                add("principle")
                add("prior")
                add("priority")
                add("privilege")
                add("probable")
                add("proceed")
                add("process")
                add("productivity")
                add("professional")
                add("proficiency")
                add("profitable")
                add("prohibit")
                add("prohibitively")
                add("project")
                add("projection")
                add("proliferation")
                add("promote")
                add("proportion")
                add("proportionally")
                add("proportions")
                add("prospect")
                add("protocol")
                add("psychology")
                add("publication")
                add("publish")
                add("purchase")
                add("pursue")
                add("pursuit")

        add("qualitative")
                add("quote")

                add("radical")
                        add("radically")
                        add("random")
                        add("range")
                        add("ratio")
                        add("rational")
                        add("react")
                        add("reasonable")
                        add("reckon")
                        add("recover")
                        add("refine")
                        add("refinery")
                        add("reflect")
                        add("regime")
                        add("region")
                        add("register")
                        add("regularly")
                        add("regulate")
                        add("reinforce")
                        add("reinforcement")
                        add("reject")
                        add("relatively")
                        add("relax")
                        add("release")
                        add("relevant")
                        add("reluctance")
                        add("reluctant")
                        add("rely")
                        add("remarkable")
                        add("remove")
                        add("rendering")
                        add("reproduction")
                        add("require")
                        add("research")
                        add("resemble")
                        add("reside")
                        add("resolve")
                        add("resource")
                        add("respond")
                        add("responsible")
                        add("restore")
                        add("restrain")
                        add("restrict")
                        add("restricted")
                        add("retain")
                        add("reveal")
                        add("revenue")
                        add("reverse")
                        add("revise")
                        add("revolution")
                        add("rigid")
                        add("ritual")
                        add("role")
                        add("roughly")
                        add("route")
                        add("routine")

                        add("savvy")
                                add("scale")
                                add("scenario")
                                add("schedule")
                                add("scheme")
                                add("scope")
                                add("sector")
                                add("secure")
                                add("seek")
                                add("select")
                                add("sequence")
                                add("series")
                                add("shift")
                                add("significance")
                                add("significant")
                                add("similar")
                                add("simulate")
                                add("simultaneously")
                                add("skeptical")
                                add("slightly")
                                add("so-called")
                                add("sole")
                                add("somewhat")
                                add("source")
                                add("specific")
                                add("specifically")
                                add("specify")
                                add("spectacular")
                                add("sphere")
                                add("stabilize")
                                add("stable")
                                add("standardise")
                                add("statistic")
                                add("stimulate")
                                add("straightforward")
                                add("strategic")
                                add("strategy")
                                add("stress")
                                add("structure")
                                add("style")
                                add("submit")
                                add("subordinate")
                                add("subsequent")
                                add("subsidy")
                                add("substantial")
                                add("substitute")
                                add("successor")
                                add("sufficient")
                                add("sufficiently")
                                add("summary")
                                add("supplement")
                                add("supplementary")
                                add("surge")
                                add("surrounded")
                                add("survey")
                                add("survive")
                                add("suspend")
                                add("sustain")
                                add("sustainable")
                                add("sustainably")
                                add("symbol")
                                add("syndrome")

        add("tape")
                add("target")
                add("technical")
                add("technique")
                add("technology")
                add("temporarily")
                add("temporary")
                add("tendency")
                add("tense")
                add("terminate")
                add("theme")
                add("theoretically")
                add("theory")
                add("thereby")
                add("therefore")
                add("thesis")
                add("threshold")
                add("towards")
                add("trace")
                add("tradition")
                add("transfer")
                add("transform")
                add("transit")
                add("transmit")
                add("transport")
                add("trend")
                add("trigger")
                add("trivial")

        add("ultimate")
                add("uncertainty")
                add("undeniable")
                add("undergo")
                add("underlie")
                add("underlying")
                add("undermine")
                add("underneath")
                add("undertake")
                add("undisputed")
                add("unethical")
                add("unfortunately")
                add("uniform")
                add("unify")
                add("unintended")
                add("unique")
                add("unlikely")
                add("unprecedented")
                add("unpredictable")
                add("unraveled")
                add("utilise")
                add("utilitarian")

        add("valid")
                add("variety")
                add("vary")
                add("vehicle")
                add("vertically")
                add("via")
                add("violate")
                add("virtual")
                add("visible")
                add("vision")
                add("visual")
                add("vital")
                add("volume")
                add("voluntary")

                add("wage")
                        add("welfare")
                        add("whereas")
                        add("whereby")
                        add("widespread")




    }
}

internal var hashMapTransition: HashMap<String, String> = object : HashMap<String, String>() {
        init {
            put("Above All", "Word: Above All::Meaning: more so than anything else:: " +
                    "synonyms: most importantly, before everything, beyond everything, first of all, most of all, chiefly, primarily, in the first place, first and foremost, mainly, principally, predominantly, especially, essentially, basically, elementally, in essence, at bottom"+
                    "::"+
                    "Type -- Transition :: Usage -- he was concerned above all to speak the truth")
            put("Earlier","Word: Earlier::Meaning: happening or done before the usual or expected time" +
                    "synonyms: untimely, premature"+
                    ":: Type -- Transition :: Usage -- we ate an early lunch")
            put("In summary","Meaning: In summary:: Type -- Transition :: Usage -- ")
            put("Accordingly","Meaning: Accordingly:: Type -- Transition :: Usage -- ")
            put("Especially","Meaning: Especially:: Type -- Transition :: Usage -- ")
            put("In the first place","Meaning: In the first place:: Type -- Transition :: Usage -- ")
            put("Singularly","Meaning: Singularly:: Type -- Transition :: Usage -- ")
            put("After","Meaning: After:: Type -- Transition :: Usage -- ")
            put("Finally","Meaning: Finally:: Type -- Transition :: Usage -- ")
            put("In the meantime","Meaning: In the meantime:: Type -- Transition :: Usage -- ")
            put("So then","Meaning: So then:: Type -- Transition :: Usage -- ")
            put("Afterward","Meaning: Afterward:: Type -- Transition :: Usage -- ")
            put("For example","Meaning: For example:: Type -- Transition :: Usage -- ")
            put("In this case","Meaning: In this case:: Type -- Transition :: Usage -- ")
            put("Soon","Meaning: Soon:: Type -- Transition :: Usage -- ")
            put("Also","Meaning: Also:: Type -- Transition :: Usage -- ")
            put("For instance","Meaning: For instance:: Type -- Transition :: Usage -- ")
            put("Incidentally","Meaning: Incidentally:: Type -- Transition :: Usage -- ")
            put("Subsequently","Meaning: Subsequently:: Type -- Transition :: Usage -- ")
            put("As a result","Meaning: As a result:: Type -- Transition :: Usage -- ")
            put("For the most part","Meaning: For the most part:: Type -- Transition :: Usage -- ")
            put("Including","Meaning: Including:: Type -- Transition :: Usage -- ")
            put("Such as","Meaning: Such as:: Type -- Transition :: Usage -- ")
            put("As a result of","Meaning: As a result of:: Type -- Transition :: Usage -- ")
            put("Furthermore","Meaning: Furthermore:: Type -- Transition :: Usage -- ")
            put("Lastly","Meaning: Lastly:: Type -- Transition :: Usage -- ")
            put("There","Meaning: There:: Type -- Transition :: Usage -- ")
            put("As a rule","Meaning: As a rule:: Type -- Transition :: Usage -- ")
            put("Generally","Meaning: Generally:: Type -- Transition :: Usage -- ")
            put("Later","Meaning: Later:: Type -- Transition :: Usage -- ")
            put("Thereby","Meaning: Thereby:: Type -- Transition :: Usage -- ")
            put("As an example","Meaning: As an example:: Type -- Transition :: Usage -- ")
            put("Hence","Meaning: Hence:: Type -- Transition :: Usage -- ")
            put("Likewise","Meaning: Likewise:: Type -- Transition :: Usage -- ")

            put("Therefore","Meaning: Therefore:: Type -- Transition :: Usage -- ")
            put("Before","Meaning: during the period of time preceding ::" +
                    "synonyms:prior to, previous to, earlier than, preparatory to, in preparation for, preliminary to, in anticipation of, in expectation of"
                    +":: Type -- Transition :: Usage -- ")
            put("Here","Meaning: Here:: Type -- Transition :: Usage -- ")
            put("Namely","Meaning: Namely:: Type -- Transition :: Usage -- ")
            put("Thus","Meaning: Thus:: Type -- Transition :: Usage -- ")
            put("Besides","Meaning: Besides:: Type -- Transition :: Usage -- ")
            put("However","Meaning: However:: Type -- Transition :: Usage -- ")
            put("Next","Meaning: Next:: Type -- Transition :: Usage -- ")
            put("To begin with","Meaning: To begin with:: Type -- Transition :: Usage -- ")
            put("Beyond","Meaning: Beyond:: Type -- Transition :: Usage -- ")
            put("In addition to","Meaning: In addition to:: Type -- Transition :: Usage -- ")
            put("Opposite","Meaning: Opposite:: Type -- Transition :: Usage -- ")
            put("To summarize","Meaning: To summarize:: Type -- Transition :: Usage -- ")
            put("By the way","Meaning: By the way:: Type -- Transition :: Usage -- ")
            put("In brief","Word: In brief::Meaning: in a few words, in short:: "+
                    "synonyms: briefly, compactly, concisely, crisply, curtly, elliptically, laconically, pithily, shortly, succinctly, summarily, tersely"
                    +"::Type -- Transition :: Usage -- he is, in brief, the embodiment of evil")
            put("Ordinarily","Meaning: Ordinarily:: Type -- Transition :: Usage -- ")
            put("To the right","Meaning: To the left or right:: Type -- Transition :: Usage -- ")
            put("To the left ","Meaning: To the left or right:: Type -- Transition :: Usage -- ")
            put("Compared to","Meaning: Compared to:: Type -- Transition :: Usage -- ")
            put("In comparison to","Meaning: In comparison to:: Type -- Transition :: Usage -- ")
            put("Otherwise","Meaning: Otherwise:: Type -- Transition :: Usage -- ")

            put("Together with","Meaning: Together with:: Type -- Transition :: Usage -- ")
            put("Consequently","Meaning: Consequently:: Type -- Transition :: Usage -- ")
            put("In conclusion","Meaning: In conclusion:: Type -- Transition :: Usage -- ")
            put("Over there","Meaning: Over there:: Type -- Transition :: Usage -- ")
            put("Under","Meaning: Under:: Type -- Transition :: Usage -- ")
            put("Conversely","Meaning: Conversely:: Type -- Transition :: Usage -- ")
            put("In particular","Meaning: In particular:: Type -- Transition :: Usage -- ")
            put("Particularly","Meaning: Particularly:: Type -- Transition :: Usage -- ")
            put("Usually","Meaning: Usually:: Type -- Transition :: Usage -- ")
            put("Coupled with","Meaning: Coupled with:: Type -- Transition :: Usage -- ")
            put("In short","Meaning: In short:: Type -- Transition :: Usage -- ")
            put("Regularly","Meaning: Regularly:: Type -- Transition :: Usage -- ")
            put("Wherefore","Meaning: Wherefore:: Type -- Transition :: Usage -- ")

        }
    }

object VocabStorage{

    internal fun getTransitionalWord():List<String>?{
        var randomNumber = (0..hashMapTransition.size).shuffled().first()
        var keys = hashMapTransition.keys
        var key = keys.elementAt(randomNumber)
        var value = hashMapTransition.get(key)
        var arr = value?.split("::")
        arr?.let {
            for(v in it){
                System.out.println(v.trim())
            }
        }
        return arr
    }

//    private fun generateRandomNumber(threshold:Int):Int{
//
//    }

}
